// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqqA8Y1qLDP0YR0Cm0oiiLEx5dELhdwgk',
    appId: '1:1078182509252:web:a8bd648f93bd27522b2791',
    messagingSenderId: '1078182509252',
    projectId: 'terreenvie-6723d',
    authDomain: 'terreenvie-6723d.firebaseapp.com',
    databaseURL: 'https://terreenvie-6723d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'terreenvie-6723d.appspot.com',
    measurementId: 'G-RSTN2X3L2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9x1lmshf7tBBDVVTBieLUjHNDf7HpLOo',
    appId: '1:1078182509252:android:d393db692712a4432b2791',
    messagingSenderId: '1078182509252',
    projectId: 'terreenvie-6723d',
    databaseURL: 'https://terreenvie-6723d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'terreenvie-6723d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCClqj77wyP0g0rXiHJcSkAjO0SbBxlmdc',
    appId: '1:1078182509252:ios:2ca7b96fd8087e9f2b2791',
    messagingSenderId: '1078182509252',
    projectId: 'terreenvie-6723d',
    databaseURL: 'https://terreenvie-6723d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'terreenvie-6723d.appspot.com',
    iosBundleId: 'com.terreenvie.terreenvie',
  );
}
